services:
  wikipedia:
    image: wiki:latest
    container_name: wikipedia
    volumes:
      - ../../data/volumes/downloader/data/wiki:/kiwix-data:ro
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true