services:
  home:
    image: home:latest
    container_name: home
    restart: always
    volumes:
      - ./app:/app
      - ./public/config.json:/application/build/client/config.json
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - frontend

networks:
  frontend:
    external: true