services:
  registry-browser:
    image: klausmeyer/docker-registry-browser:1.8.3
    container_name: registry-browser
    environment:
      - "SECRET_KEY_BASE=cTpIR0MdZw7zL5C37jKizDJHkuOyz+o6zIcIXXSjwiE="
      - "DOCKER_REGISTRY_URL=http://registry:5000"
      - "ENABLE_DELETE_IMAGES=true"
      - "PUBLIC_REGISTRY_URL=reg.root:5000"
    restart: unless-stopped
    networks:
      - frontend
  registry:
    image: registry:3.0.0
    container_name: registry
    volumes:
      - ../../data/volumes/registry/registry:/var/lib/registry
      - ../../data/volumes/registry/config.yaml:/etc/docker/registry/config.yml:ro
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=false
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true