services:
  downloader:
    image: downloader:latest
    privileged: true
    volumes:
      - ../../data/volumes/downloader/data:/usr/local/data
      - ../../data/volumes/downloader/logs:/logs
      - ../../data/volumes/downloader/config:/config:ro
      - ../../data/volumes/downloader/mirror-rsync.d:/usr/local/bin/scripts/mirror-rsync.d
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true