services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data:/usr/local/data
      - ./logs:/logs
      - ./mirror-rsync.d:/usr/local/bin/scripts/mirror-rsync.d
    restart: unless-stopped
