services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_TLS_SAN=reg.root
    volumes:
      - ../../data/volumes/downloader/data:/usr/local/data
      - ../../data/volumes/downloader/logs:/logs
      - ../../data/volumes/downloader/config:/config:ro
      - ../../data/volumes/downloader/mirror-rsync.d:/usr/local/bin/scripts/mirror-rsync.d
      - downloader-certs:/certs
      - downloader-docker:/var/lib/docker
    networks:
      - homelab
    restart: unless-stopped

volumes:
  downloader-certs:
  downloader-docker:

networks:
  homelab:
    external: true 