services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data/volumes/downloader/data:/usr/local/data
      - ../../data/volumes/downloader/logs:/logs
      - ../../data/volumes/downloader/config:/config:ro
      - ../../data/volumes/downloader/mirror-rsync.d:/usr/local/bin/scripts/mirror-rsync.d
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped 