services:
  coredns:
    image: coredns/coredns:1.12.1
    container_name: coredns
    restart: always
    volumes:
      - ../../data/volumes/coredns/config:/root
    ports:
      - "8053:8053/udp"
    command: -conf /root/Corefile
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
        tag: "coredns"
    networks:
      - frontend

networks:
  frontend:
    external: true