services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../../data/volumes/nginx/conf/sites.conf:/etc/nginx/conf.d/sites.conf:ro
      - ../../data/volumes/downloader/data/files:/var/www/files:ro
      - ../../data/volumes/downloader/data/packages:/var/www/apt-mirror:ro
      - ../../data/volumes/nginx/logs:/var/log/nginx:rw
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true