services:
  nginx:
    image: nginx:1.28.0-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .../../data/volumes/nginx/conf/sites.conf:/etc/nginx/conf.d/sites.conf:ro
      - ../../data/volumes/downloader/files:/var/www/files:ro
      - ../../data/volumes/downloader/packages:/var/www/apt-mirror:ro
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true