services:
  gogs:
    image: gogs:0.13
    hostname: gogs
    environment:
      - GOGS_CUSTOM_PATH=/data/gogs
    volumes:
      - ../../data/volumes/gogs/gogs:/data/gogs
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true
